# Generated by Django 5.1.6 on 2025-04-29 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_order_date_order_ordered_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customization_text',
            new_name='customization',
        ),
    ]
